<?php

function stringCommands(string $string, array $commands): string
{
  foreach ($commands as $command => $value) {
    $string = str_replace($command, $value, $string);
  }
  return $string;
}

function commands(array $config = [], array $core = [], string $slug = "", string $url = "", string $url_not_index = "", string $theme = "", string $dir = "", bool $auth = false, array $post = [], string $viewAdsMessajeAndBanner = "", string $viewAdsThumbnail = "", string $viewAlertMessage = "", string $viewsRequire = "", string $viewComments = ""): array
{
  return [
    "{{ post_content }}" => $post["content"] ?? "",
    "{{ page_name }}" => $config["page_name"] ?? "daam",
    "{{ page_link }}" => $config["page_link"] ?? "https://github.com/armindeck",
    "{{ page_timezone }}" => $config["page_timezone"] ?? "America/Bogota",
    "{{ page_language }}" => $config["page_language"] ?? "es",
    "{{ page_template }}" => $config["page_template"] ?? "classic",
    "{{ page_theme }}" => $config["page_theme"] ?? "light",
    "{{ page_style }}" => $config["page_style"] ?? "classic.css",
    "{{ page_year }}" => $config["page_year"] ?? "2026",
    "{{ page_about }}" => $config["page_about"] ?? "Esta es una página web creada con el CMS Daam ArminVT.",
    "{{ page_tags }}" => $config["page_tags"] ?? "armionegai.rf.gd, dbproject.rf.gd",
    "{{ page_scripts }}" => $config["page_scripts"] ?? "<!-- Google Ads/Analitycs, Font Awesome, Other... -->",
    "{{ page_scripts_active }}" => $config["page_scripts_active"] ?? false,
    "{{ page_ssl_active }}" => $config["page_ssl_active"] ?? false,
    "{{ page_extension_php_active }}" => $config["page_extension_php_active"] ?? false,
    "{{ core_name }}" => $core["core_name"] ?? "daam",
    "{{ core_link }}" => $core["core_link"] ?? "https://github.com/armindeck/daam-arminvt",
    "{{ core_version }}" => $core["core_version"] ?? "0.0.0",
    "{{ core_state }}" => $core["core_state"] ?? "dev",
    "{{ core_updated }}" => $core["core_updated"] ?? "0000-00-00",
    "{{ core_created }}" => $core["core_created"] ?? "0000-00-00",
    "{{ core_about }}" => $core["core_about"] ?? "Página web para ForoLink, Juegos, Animes, Proyectos, Blogs con múltiples temas personalizados, Panel administrativo avanzado con muchas funciones para la personalización de la página, extensiones y muchas otras cosas.",
    "{{ core_creator_name }}" => $core["core_creator_name"] ?? "Armin Deck",
    "{{ core_creator_link }}" => $core["core_creator_link"] ?? "https://github.com/armindeck",
    "{{ SLUG }}" => $slug,
    "{{ DIR }}" => $dir,
    "{{ URL }}" => $url,
    "{{ URL_NOT_INDEX }}" => $url_not_index,
    "{{ linkChangeTheme }}" => '<a href="?theme=' . ($theme == "dark" ? "light" : "dark") . '"><i class="fas fa-' . ($theme == "dark" ? "sun" : "moon") . '"></i></a>',
    "{{ linkLogout }}" => $auth ? '<a href="?logout=true">Salir</a>' : '',
    "{{ linkIconLogout }}" => $auth ? '<a href="?logout=true"><i class="fas fa-sign-out-alt"></i></a>' : '',
    "{{ linkAndIconLogout }}" => $auth ? '<a href="?logout=true"><i class="fas fa-sign-out-alt"></i> Salir</a>' : '',
    "{{ linkLogoutFalse }}" => $auth ? '<a href="?logout=false">Salir</a>' : '',
    "{{ linkIconLogoutFalse }}" => $auth ? '<a href="?logout=false"><i class="fas fa-sign-out-alt"></i></a>' : '',
    "{{ linkAndIconLogoutFalse }}" => $auth ? '<a href="?logout=false"><i class="fas fa-sign-out-alt"></i> Salir</a>' : '',
    "{{ viewAdsMessajeAndBanner }}" => $viewAdsMessajeAndBanner,
    "{{ viewAdsThumbnail }}" => $viewAdsThumbnail,
    "{{ viewAlertMessage }}" => $viewAlertMessage,
    "{{ viewsRequire }}" => $viewsRequire,
    "{{ viewComments }}" => $viewComments,
    "img[http" => "<img src=\"http",
    "img[" => "<img src=\"" . $dir . "assets/img/",
    "]img;" => "\" loading=\"lazy\">",
    "video-iframe[" => "<iframe width=\"800\" height=\"450\" src=\"",
    "]video-iframe;" => "\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
    "icon[" => "<i class=\"",
    "]icon;" => "\"></i>",
    "link[" => "<a href=\"",
    "link-external[" => "<a target=\"_blank\" href=\"",
    "link-ignore[" => "<a target=\"_blank\" rel=\"nofollow noreferrer\" href=\"",
    "link-dir[" => "<a href=\"" . $dir,
    "link-dir-external[" => "<a target=\"_blank\" href=\"" . $dir,
    "link-dir-ignore[" => "<a target=\"_blank\" rel=\"nofollow noreferrer\" href=\"" . $dir,
    "link-dir-text[" => "<a href=\"" . $dir . "\">",
    "link-dir-text-external[" => "<a target=\"_blank\" href=\"" . $dir . "\">",
    "link-dir-text-ignore[" => "<a target=\"_blank\" rel=\"nofollow noreferrer\" href=\"" . $dir . "\">",
    "]link;" => "</a>",
    "text-field[" => "<span class=\"text-field\">",
    "text-field-small[" => "<span class=\"text-field text-field-small\">",
    "text-field-mini[" => "<span class=\"text-field text-field-mini\">",
    "text-field-mini-small[" => "<span class=\"text-field text-field-mini text-field-mini-small\">",
    "]text-field;" => "</span>",
    "p[" => "<p>",
    "]p;" => "</p>",
    "strong[" => "<strong>",
    "]strong;" => "</strong>",
    "*[" => "<strong>",
    "]*;" => "</strong>",
    "small[" => "<small>",
    "]small;" => "</small>",
    "italic[" => "<i>",
    "]italic;" => "</i>",
    "~[" => "<i>~ ",
    "]~;" => "</i>",
    "items[" => "<ul>",
    "]items;" => "</ul>",
    "list[" => "<ol>",
    "]list;" => "</ol>",
    "item[" => "<li>",
    "]item;" => "</li>",
    "section[" => "<section>",
    "]section;" => "</section>",
    "content[" => "<div class=\"con\">",
    "]content;" => "</div>",
    "div[" => "<div>",
    "]div;" => "</div>",
    "details[" => "<details>",
    "details-open[" => "<details open>",
    "]details;" => "</section></details>",
    "summary[" => "<summary>",
    "]summary;" => "</summary><section>",
    "center[" => "<center>",
    "]center;" => "</center>",
    "h1[" => "<h1>",
    "]h1;" => "</h1>",
    "h2[" => "<h2>",
    "]h2;" => "</h2>",
    "h3[" => "<h3>",
    "]h3;" => "</h3>",
    "h4[" => "<h4>",
    "]h4;" => "</h4>",
    "h5[" => "<h5>",
    "]h5;" => "</h5>",
    "h6[" => "<h6>",
    "]h6;" => "</h6>",
    "]/[" => "\">",
    "`<`" => "&lt;",
    "`>`" => "&gt;",
    "button[" => "<a class=\"boton\" href=\"",
    "button-external[" => "<a class=\"boton\" target=\"_blank\" href=\"",
    "button-ignore[" => "<a class=\"boton\" target=\"_blank\" rel=\"nofollow noreferrer\" href=\"",
    "button-mini[" => "<a class=\"boton boton-mini\" href=\"",
    "button-mini-external[" => "<a class=\"boton boton-mini\" target=\"_blank\" href=\"",
    "button-mini-ignore[" => "<a class=\"boton boton-mini\" target=\"_blank\" rel=\"nofollow noreferrer\" href=\"",
    "button-2[" => "<a class=\"boton-2\" href=\"",
    "button-2-external[" => "<a class=\"boton-2\" target=\"_blank\" href=\"",
    "button-2-ignore[" => "<a class=\"boton-2\" target=\"_blank\" rel=\"nofollow noreferrer\" href=\"",
    "button-2-mini[" => "<a class=\"boton-2 boton-mini\" href=\"",
    "button-2-mini-external[" => "<a class=\"boton-2 boton-mini\" target=\"_blank\" href=\"",
    "button-2-mini-ignore[" => "<a class=\"boton-2 boton-mini\" target=\"_blank\" rel=\"nofollow noreferrer\" href=\"",
    "]button;" => "</a>",
    "`-`" => "<span style=\"margin-left: 16;\"></span>",
    "`--`" => "<span style=\"margin-left: 32px;\"></span>",
    "`---`" => "<span style=\"margin-left: 48px;\"></span>",
    "`----`" => "<span style=\"margin-left: 64px;\"></span>",
    "`-----`" => "<span style=\"margin-left: 80px;\"></span>",
    "`------`" => "<span style=\"margin-left: 96px;\"></span>",
    "`-------`" => "<span style=\"margin-left: 112px;\"></span>",
    "`--------`" => "<span style=\"margin-left: 128px;\"></span>",
    "`---------`" => "<span style=\"margin-left: 144px;\"></span>",
    "`----------`" => "<span style=\"margin-left: 160px;\"></span>",
    "***** DEFECTUOSOS *****" => "***** DEFECTUOSOS *****",
    "img{" => "<img loading=\"lazy\" src=\"",
    "imgl{" => "<img loading=\"lazy\" src=\"" . $dir . "assets/img/",
    "iframe{" => "<iframe width=\"800\" height=\"450\" src=\"",
    "}iframe;" => "\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
    "};" => "\">",
    "ul[" => "<ul>",
    "]/ul" => "</ul>",
    "b[" => "<strong>",
    "]/b" => "</strong>",
    "]/~" => "</i>",
    "]/section" => "</section>",
    "]/details" => "</section></details>",
    "]/details-open" => "</section></details>",
    "]/summary" => "</summary><section>",
    "]/h1" => "</h1>",
    "]/h2" => "</h2>",
    "]/h3" => "</h3>",
    "]/h4" => "</h4>",
    "]/h5" => "</h5>",
    "]/h6" => "</h6>"
  ];
}

function commandsTemplateUserComponents(array $components): array
{
  $cmds = [];
  foreach ($components as $key => $value) {
    $cmds["{{ component." . ($value["id"] ?? "") . " }}"] = $value["layout"] ?? "";
  }
  return $cmds;
}